### ISSUE TITLE
Multiplatform?

### ISSUE THREAD

**Issue by Dominaezzz** [koma-im/koma-library#1]
Hi there! I was thinking of making a Matrix client in Kotlin and I found your project.
I was looking at making it multiplatform (JS and some native targets) but doing that will require breaking changes 😬 , since some of the libraries you use aren't multiplatform. Like using `kotlinx.serialization` instead of `Jackson` and potentially Ktor instead of Retrofit.

Is this a deal breaker? 😄

**Comment by yuforia** [comment]
@Dominaezzz I have been interested in Kotlin/Native and Ktor, but since json serialization/deserialization make up the majority of the project, the change may be like rewriting a new library to some extent. And the current dependencies seem to be performant enough, so I haven't spent much time looking into multiplatform ones
